name: Check Eventbrite and update RSS

on:
  schedule:
    - cron: '2 * * * *'  # 毎時2分に実行
  workflow_dispatch:     # 手動実行も可能

jobs:
  build:
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト（PAT を使用）
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      # Python をセットアップ
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 依存関係インストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # スクリプト実行
      - name: Run checker
        run: python check_eventbrite.py

      # 変更があればコミット & push
      - name: Commit RSS if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add feed.xml seen.json
          if ! git diff --cached --quiet; then
            git commit -m "Update feed and seen files" || echo "No changes to commit"
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
            git push
          else
            echo "No changes to commit"
          fi
